/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IHypervisorFactory,
  IHypervisorFactoryInterface,
} from "../IHypervisorFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token0",
        type: "address",
      },
      {
        internalType: "address",
        name: "token1",
        type: "address",
      },
      {
        internalType: "uint24",
        name: "fee",
        type: "uint24",
      },
    ],
    name: "getHypervisor",
    outputs: [
      {
        internalType: "address",
        name: "hypervisor",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IHypervisorFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IHypervisorFactoryInterface {
    return new utils.Interface(_abi) as IHypervisorFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IHypervisorFactory {
    return new Contract(address, _abi, signerOrProvider) as IHypervisorFactory;
  }
}
