/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface HypervisorV3MigratorInterface extends ethers.utils.Interface {
  functions: {
    "migrate(address,uint8,address)": FunctionFragment;
    "uniProxy()": FunctionFragment;
    "uniswapV2Factory()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "migrate",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "uniProxy", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "uniswapV2Factory",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "migrate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "uniProxy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "uniswapV2Factory",
    data: BytesLike
  ): Result;

  events: {};
}

export class HypervisorV3Migrator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: HypervisorV3MigratorInterface;

  functions: {
    migrate(
      _hypervisor: string,
      percentageToMigrate: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    uniProxy(overrides?: CallOverrides): Promise<[string]>;

    uniswapV2Factory(overrides?: CallOverrides): Promise<[string]>;
  };

  migrate(
    _hypervisor: string,
    percentageToMigrate: BigNumberish,
    recipient: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  uniProxy(overrides?: CallOverrides): Promise<string>;

  uniswapV2Factory(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    migrate(
      _hypervisor: string,
      percentageToMigrate: BigNumberish,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    uniProxy(overrides?: CallOverrides): Promise<string>;

    uniswapV2Factory(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    migrate(
      _hypervisor: string,
      percentageToMigrate: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    uniProxy(overrides?: CallOverrides): Promise<BigNumber>;

    uniswapV2Factory(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    migrate(
      _hypervisor: string,
      percentageToMigrate: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    uniProxy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    uniswapV2Factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
